package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.avisos.Aviso;
import com.itson.bdavanzadas.negocio.IPersonasBO;
import com.itson.bdavanzadas.negocio.PersonasBO;
import org.itson.bdavanzadas.conexion.Conexion;
import org.itson.bdavanzadas.conexion.IConexion;
import org.itson.bdavanzadas.daos.IPersonasDAO;
import org.itson.bdavanzadas.daos.PersonasDAO;

/**
 *
 * Clase que representa la vista de inicio o menu principal de la aplicación.
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaInicio extends javax.swing.JPanel {

    private Ventana ventana;
    private IConexion conexion = new Conexion();
    private IPersonasBO personasBO = new PersonasBO();

    /**
     * Constructor de la clase VistaInicio.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaInicio(Ventana ventana) {
        this.ventana = ventana;
        this.personasBO = new PersonasBO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramitarPlaca = new javax.swing.JButton();
        btnTramitesDisponibles = new javax.swing.JButton();
        btnTramitesEnCurso = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        btnModuloReportes = new javax.swing.JButton();
        btnInsercionMasiva = new javax.swing.JButton();
        btnTramitarLicencia = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoInfo = new javax.swing.JLabel();
        lblTramitesDisponibles = new javax.swing.JLabel();
        lblTramitesPendientes = new javax.swing.JLabel();
        lblModuloConsultas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        lblTramitarPlaca = new javax.swing.JLabel();
        lblTramitarPlaca1 = new javax.swing.JLabel();
        iconPlaca = new javax.swing.JLabel();
        iconLicencia = new javax.swing.JLabel();
        iconIsercionMasiva = new javax.swing.JLabel();
        lblInsercionMasiva = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitarPlaca.setBorder(null);
        btnTramitarPlaca.setBorderPainted(false);
        btnTramitarPlaca.setContentAreaFilled(false);
        btnTramitarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitarPlacaActionPerformed(evt);
            }
        });
        add(btnTramitarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 184, 150, 145));

        btnTramitesDisponibles.setBorder(null);
        btnTramitesDisponibles.setBorderPainted(false);
        btnTramitesDisponibles.setContentAreaFilled(false);
        btnTramitesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesDisponiblesActionPerformed(evt);
            }
        });
        add(btnTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 128, 40));

        btnTramitesEnCurso.setBorder(null);
        btnTramitesEnCurso.setBorderPainted(false);
        btnTramitesEnCurso.setContentAreaFilled(false);
        btnTramitesEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesEnCursoActionPerformed(evt);
            }
        });
        add(btnTramitesEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 128, 40));

        btnModuloConsultas.setBorder(null);
        btnModuloConsultas.setBorderPainted(false);
        btnModuloConsultas.setContentAreaFilled(false);
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 128, 40));

        btnModuloReportes.setBorder(null);
        btnModuloReportes.setBorderPainted(false);
        btnModuloReportes.setContentAreaFilled(false);
        btnModuloReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloReportesActionPerformed(evt);
            }
        });
        add(btnModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 128, 40));

        btnInsercionMasiva.setBorder(null);
        btnInsercionMasiva.setBorderPainted(false);
        btnInsercionMasiva.setContentAreaFilled(false);
        btnInsercionMasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercionMasivaActionPerformed(evt);
            }
        });
        add(btnInsercionMasiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 184, 150, 145));

        btnTramitarLicencia.setBorder(null);
        btnTramitarLicencia.setBorderPainted(false);
        btnTramitarLicencia.setContentAreaFilled(false);
        btnTramitarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitarLicenciaActionPerformed(evt);
            }
        });
        add(btnTramitarLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 184, 150, 145));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(196, 4, 67));
        lblTitulo.setText("Tramites disponibles");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSol.png"))); // NOI18N
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 60, 60));

        lblLogoInfo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblLogoInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoInfo.setText("Agencia del Sol");
        add(lblLogoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 16, 260, 43));

        lblTramitesDisponibles.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesDisponibles.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesDisponibles.setText("<html>Trámites<br>disponibles</html>");
        add(lblTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 105, 87, 34));

        lblTramitesPendientes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesPendientes.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesPendientes.setText("<html>Trámites<br>en curso</html>");
        add(lblTramitesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 160, 87, 34));

        lblModuloConsultas.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblModuloConsultas.setForeground(new java.awt.Color(196, 4, 67));
        lblModuloConsultas.setText("<html>Modulo<br>consultas</html>");
        add(lblModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 215, 87, 34));

        lblReportes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(196, 4, 67));
        lblReportes.setText("<html>Modulo<br>reportes</html>");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 270, 87, 34));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramiteDisponibles.png"))); // NOI18N
        add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 40, 40));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramitesEnCurso.png"))); // NOI18N
        add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 40, 40));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConsultas.png"))); // NOI18N
        add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 40, 40));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReporte.png"))); // NOI18N
        add(lblLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 40, 40));

        lblTramitarPlaca.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblTramitarPlaca.setForeground(new java.awt.Color(247, 242, 244));
        lblTramitarPlaca.setText("Tramitar Placa");
        add(lblTramitarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        lblTramitarPlaca1.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblTramitarPlaca1.setForeground(new java.awt.Color(247, 242, 244));
        lblTramitarPlaca1.setText("Insercion masiva");
        add(lblTramitarPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        iconPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPlaca.png"))); // NOI18N
        add(iconPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 195, 95, 95));

        iconLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLicencia.png"))); // NOI18N
        add(iconLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 195, 95, 95));

        iconIsercionMasiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconInsercionMasiva.png"))); // NOI18N
        add(iconIsercionMasiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 194, 90, 90));

        lblInsercionMasiva.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblInsercionMasiva.setForeground(new java.awt.Color(247, 242, 244));
        lblInsercionMasiva.setText("Tramitar Licencia");
        add(lblInsercionMasiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 300, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaInicio2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites en curso".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites en curso").
     */
    private void btnTramitesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesDisponiblesActionPerformed
    }//GEN-LAST:event_btnTramitesDisponiblesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites disponibles".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites disponibles").
     */
    private void btnTramitesEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesEnCursoActionPerformed
        if (ventana.isSeHizoInsercion()) {
            ventana.cambiarVistaTramitesEnCurso();
        } else {
            new Aviso().mostrarAviso(ventana, "Haga inserción masiva primero");
        }
    }//GEN-LAST:event_btnTramitesEnCursoActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo consultas".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo consultas").
     */
    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed
        if (ventana.isSeHizoInsercion()) {
            ventana.cambiarVistaModuloConsultas();
        } else {
            new Aviso().mostrarAviso(ventana, "Haga inserción masiva primero");
        }
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo reportes".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo reportes").
     */
    private void btnModuloReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloReportesActionPerformed
        ventana.cambiarVistaModuloReporte();
    }//GEN-LAST:event_btnModuloReportesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámitar placa".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites trámitar").
     */
    private void btnTramitarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitarPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTramitarPlacaActionPerformed

    /**
     * Maneja el evento de acción del botón de inserción masiva.
     *
     * @param evt El evento de acción asociado al botón de inserción masiva.
     */
    private void btnInsercionMasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionMasivaActionPerformed
        if (ventana.isSeHizoInsercion()) {
            new Aviso().mostrarAviso(ventana, "Ya hizo la insercion masiva");
        } else {
            personasBO.incersionMasivaPersonas();
            ventana.setSeHizoInsercion(true);
        }
    }//GEN-LAST:event_btnInsercionMasivaActionPerformed

    /**
     * Maneja el evento de acción del botón de tramitar licencia.
     *
     * @param evt El evento de acción asociado al botón de tramitar licencia.
     */
    private void btnTramitarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitarLicenciaActionPerformed
        if (ventana.isSeHizoInsercion()) {
            ventana.cambiarVistaPersonaATramitar();
        } else {
            new Aviso().mostrarAviso(ventana, "Haga inserción masiva primero");
        }
    }//GEN-LAST:event_btnTramitarLicenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsercionMasiva;
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloReportes;
    private javax.swing.JButton btnTramitarLicencia;
    private javax.swing.JButton btnTramitarPlaca;
    private javax.swing.JButton btnTramitesDisponibles;
    private javax.swing.JButton btnTramitesEnCurso;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconIsercionMasiva;
    private javax.swing.JLabel iconLicencia;
    private javax.swing.JLabel iconPlaca;
    private javax.swing.JLabel lblInsercionMasiva;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblLogoInfo;
    private javax.swing.JLabel lblModuloConsultas;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTramitarPlaca;
    private javax.swing.JLabel lblTramitarPlaca1;
    private javax.swing.JLabel lblTramitesDisponibles;
    private javax.swing.JLabel lblTramitesPendientes;
    // End of variables declaration//GEN-END:variables

}
