/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package org.itson.bdavanzadas.agenciadelsol;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 244802
 */
public class VistaInicio extends javax.swing.JPanel {

    /** Creates new form VistaInicio */
    public VistaInicio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEncabezado = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panSeparador = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panTramitarLicencia = new javax.swing.JPanel();
        btnTramitarLicencia = new javax.swing.JButton();
        panDescripcion1 = new javax.swing.JPanel();
        lblTramitarPlaca1 = new javax.swing.JLabel();
        panTramitarPlaca = new javax.swing.JPanel();
        btnTramitarPlaca = new javax.swing.JButton();
        panDescripcion = new javax.swing.JPanel();
        lblTramitarPlaca = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panEncabezado.setBackground(new java.awt.Color(191, 3, 57));
        panEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("Agencia del Sol");
        panEncabezado.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 16, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSol.png"))); // NOI18N
        jLabel1.setToolTipText("");
        panEncabezado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 8, 60, 60));

        add(panEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        panSeparador.setBackground(new java.awt.Color(239, 177, 197));

        javax.swing.GroupLayout panSeparadorLayout = new javax.swing.GroupLayout(panSeparador);
        panSeparador.setLayout(panSeparadorLayout);
        panSeparadorLayout.setHorizontalGroup(
            panSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panSeparadorLayout.setVerticalGroup(
            panSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        add(panSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 13));

        jPanel1.setBackground(new java.awt.Color(239, 177, 197));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 165, 489));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(196, 4, 67));
        lblTitulo.setText("Tramites disponibles");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        panTramitarLicencia.setBackground(new java.awt.Color(239, 177, 197));
        panTramitarLicencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitarLicencia.setContentAreaFilled(false);
        panTramitarLicencia.add(btnTramitarLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 146));

        panDescripcion1.setBackground(new java.awt.Color(215, 70, 118));
        panDescripcion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTramitarPlaca1.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblTramitarPlaca1.setForeground(new java.awt.Color(247, 242, 244));
        lblTramitarPlaca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTramitarPlaca1.setText("Tramitar Licencia");
        panDescripcion1.add(lblTramitarPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 138, -1));

        panTramitarLicencia.add(panDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 150, 33));

        add(panTramitarLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, 146));

        panTramitarPlaca.setBackground(new java.awt.Color(239, 177, 197));
        panTramitarPlaca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitarPlaca.setContentAreaFilled(false);
        panTramitarPlaca.add(btnTramitarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 146));

        panDescripcion.setBackground(new java.awt.Color(215, 70, 118));
        panDescripcion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTramitarPlaca.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblTramitarPlaca.setForeground(new java.awt.Color(247, 242, 244));
        lblTramitarPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTramitarPlaca.setText("Tramitar Placa");
        panDescripcion.add(lblTramitarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 138, -1));

        panTramitarPlaca.add(panDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 150, 33));

        add(panTramitarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 146));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTramitarLicencia;
    private javax.swing.JButton btnTramitarPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTramitarPlaca;
    private javax.swing.JLabel lblTramitarPlaca1;
    private javax.swing.JPanel panDescripcion;
    private javax.swing.JPanel panDescripcion1;
    private javax.swing.JPanel panEncabezado;
    private javax.swing.JPanel panSeparador;
    private javax.swing.JPanel panTramitarLicencia;
    private javax.swing.JPanel panTramitarPlaca;
    // End of variables declaration//GEN-END:variables

}
