package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.avisos.Aviso;
import com.itson.bdavanzadas.dtos.ConsultarPersonaDTO;
import com.itson.bdavanzadas.dtos.TramiteDTO;
import com.itson.bdavanzadas.excepcionesdtos.ValidacionDTOException;
import com.itson.bdavanzadas.negocio.IPersonasBO;
import com.itson.bdavanzadas.negocio.ITramitesBO;
import com.itson.bdavanzadas.negocio.PersonasBO;
import com.itson.bdavanzadas.negocio.TramitesBO;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.PersistenceException;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que representa la vista del módulo de consultas en la aplicación.
 * 
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaModuloConsultas extends javax.swing.JPanel {

    private Ventana ventana;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private IPersonasBO personasBO;
    private ITramitesBO tramitesBO;
    List<ConsultarPersonaDTO> personas;
    private boolean isChecked = false;

    /**
     * Constructor de la clase VistaInicio.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaModuloConsultas(Ventana ventana) {
        this.ventana = ventana;
        this.tramitesBO = new TramitesBO();
        this.personasBO = new PersonasBO();
        this.personas = personasBO.consultarPersonas();
        initComponents();
        actualizarTabla(personas);
        txtNombrePersona.setEnabled(false);
        dpFechaNacimiento.setEnabled(false);
        txtRfc.setEnabled(false);
        
    }
    
     /**
     * Metodo para limpiar la tabla de Reportes.
     */
    private void limpiarTabla() {
        modeloTabla = (DefaultTableModel) tblPersonas.getModel();
        if (modeloTabla.getRowCount() > 0) {
            for (int i = modeloTabla.getRowCount() - 1; i > -1; i--) {
                modeloTabla.removeRow(i);
            }
        }
    }
    
    /** 
     * Metodo que actualiza la tabla de personas, mostrando los datos necesarios.
     * @param personas lista de personas a plasmar.
     */
    private void actualizarTabla(List<ConsultarPersonaDTO> personas) {
        try {
            DefaultTableModel personasTabla = new DefaultTableModel();
            personasTabla.addColumn("Nombre");
            personasTabla.addColumn("Discapacitado");
            personasTabla.addColumn("Fecha Nacimiento");
            personasTabla.addColumn("RFC");

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            Calendar fechaActual = Calendar.getInstance();

            for (ConsultarPersonaDTO persona : personas) {
                Calendar fechaNacimiento = persona.getFechaNacimiento();
                int edad = fechaActual.get(Calendar.YEAR) - fechaNacimiento.get(Calendar.YEAR);

                if (fechaNacimiento.get(Calendar.MONTH) < fechaActual.get(Calendar.MONTH)
                        || (fechaNacimiento.get(Calendar.MONTH) == fechaActual.get(Calendar.MONTH)
                        && fechaNacimiento.get(Calendar.DAY_OF_MONTH) <= fechaActual.get(Calendar.DAY_OF_MONTH))) {
                    edad++;
                }
                if (edad >= 18) {
                    String fechaFormateada = dateFormat.format(fechaNacimiento.getTime());
                    Object[] fila = {
                        persona.getNombres() + " " + persona.getApellidoPaterno(),
                        persona.getDiscapacidad(),
                        fechaFormateada,
                        persona.getRfc()
                    };

                    personasTabla.addRow(fila); 
                }
            }

            tblPersonas.setModel(personasTabla);
            tblPersonas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Solo se puede seleccionar una fila a la vez
            tblPersonas.setDefaultEditor(Object.class, null); // Deshabilita la edición de celdas
        } catch (PersistenceException ex) {
            Logger.getLogger(VistaModuloReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramitesDisponibles = new javax.swing.JButton();
        btnTramitesEnCurso = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        btnModuloReportes = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoInfo = new javax.swing.JLabel();
        lblTramitesDisponibles = new javax.swing.JLabel();
        lblTramitesPendientes = new javax.swing.JLabel();
        lblModuloConsultas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        lblNombrePersona = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        lblCheck1 = new javax.swing.JLabel();
        lblCheck2 = new javax.swing.JLabel();
        lblCheck3 = new javax.swing.JLabel();
        dpFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        txtNombrePersona = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitesDisponibles.setBorder(null);
        btnTramitesDisponibles.setBorderPainted(false);
        btnTramitesDisponibles.setContentAreaFilled(false);
        btnTramitesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesDisponiblesActionPerformed(evt);
            }
        });
        add(btnTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 128, 40));

        btnTramitesEnCurso.setBorder(null);
        btnTramitesEnCurso.setBorderPainted(false);
        btnTramitesEnCurso.setContentAreaFilled(false);
        btnTramitesEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesEnCursoActionPerformed(evt);
            }
        });
        add(btnTramitesEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 128, 40));

        btnModuloConsultas.setBorder(null);
        btnModuloConsultas.setBorderPainted(false);
        btnModuloConsultas.setContentAreaFilled(false);
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 128, 40));

        btnModuloReportes.setBorder(null);
        btnModuloReportes.setBorderPainted(false);
        btnModuloReportes.setContentAreaFilled(false);
        btnModuloReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloReportesActionPerformed(evt);
            }
        });
        add(btnModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 128, 40));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(196, 4, 67));
        lblTitulo.setText("Módulo de consultas");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 107, 337, 43));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSol.png"))); // NOI18N
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 60, 60));

        lblLogoInfo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblLogoInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoInfo.setText("Agencia del Sol");
        add(lblLogoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 16, 260, 43));

        lblTramitesDisponibles.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesDisponibles.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesDisponibles.setText("<html>Trámites<br>disponibles</html>");
        add(lblTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 105, 87, 34));

        lblTramitesPendientes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesPendientes.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesPendientes.setText("<html>Trámites<br>en curso</html>");
        add(lblTramitesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 160, 87, 34));

        lblModuloConsultas.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblModuloConsultas.setForeground(new java.awt.Color(196, 4, 67));
        lblModuloConsultas.setText("<html>Modulo<br>consultas</html>");
        add(lblModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 215, 87, 34));

        lblReportes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(196, 4, 67));
        lblReportes.setText("<html>Modulo<br>reportes</html>");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 270, 87, 34));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramiteDisponibles.png"))); // NOI18N
        add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 40, 40));

        lblBuscar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(196, 4, 67));
        lblBuscar.setText("Buscar por:");
        add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 164, 122, 29));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramitesEnCurso.png"))); // NOI18N
        add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 40, 40));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConsultas.png"))); // NOI18N
        add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 40, 40));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReporte.png"))); // NOI18N
        add(lblLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 40, 40));

        lblNombrePersona.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblNombrePersona.setForeground(new java.awt.Color(215, 70, 118));
        lblNombrePersona.setText("Nombre de la persona:");
        add(lblNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 209, 200, 24));

        lblFechaNacimiento.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(215, 70, 118));
        lblFechaNacimiento.setText("Fecha de nacimiento:");
        add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 180, 24));

        lblCurp.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblCurp.setForeground(new java.awt.Color(215, 70, 118));
        lblCurp.setText("RFC:");
        add(lblCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 211, 40, 24));

        lblCheck1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCheck1MouseClicked(evt);
            }
        });
        add(lblCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 213, 20, 20));

        lblCheck2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCheck2MouseClicked(evt);
            }
        });
        add(lblCheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 213, 20, 20));

        lblCheck3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCheck3MouseClicked(evt);
            }
        });
        add(lblCheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 213, 20, 20));
        add(dpFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 241, 200, 36));

        txtNombrePersona.setBackground(new java.awt.Color(247, 242, 244));
        txtNombrePersona.setBorder(null);
        txtNombrePersona.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtNombrePersona.setForeground(new java.awt.Color(143, 143, 143));
        add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 241, 245, 36));

        txtRfc.setBackground(new java.awt.Color(247, 242, 244));
        txtRfc.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtRfc.setForeground(new java.awt.Color(143, 143, 143));
        txtRfc.setBorder(null);
        add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 241, 228, 35));

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorder(null);
        btnSeleccionar.setContentAreaFilled(false);
        btnSeleccionar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(253, 253, 253));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 484, 186, 45));

        btnVolver.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(253, 253, 253));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 484, 142, 45));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.setBorder(null);
        btnFiltrar.setContentAreaFilled(false);
        btnFiltrar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(253, 253, 253));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 164, 142, 45));

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Discapacitado", "Fecha Nacimiento", "RFC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPersonas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 780, 190));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaModuloConsulta.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites en curso".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites en curso").
     */
    private void btnTramitesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesDisponiblesActionPerformed
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnTramitesDisponiblesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites disponibles".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites disponibles").
     */
    private void btnTramitesEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesEnCursoActionPerformed
        ventana.cambiarVistaTramitesEnCurso();
    }//GEN-LAST:event_btnTramitesEnCursoActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo consultas".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo consultas").
     */
    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed
        ventana.cambiarVistaModuloConsultas();
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo reportes".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo reportes").
     */
    private void btnModuloReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloReportesActionPerformed
        ventana.cambiarVistaModuloReporte();
    }//GEN-LAST:event_btnModuloReportesActionPerformed

    /**
     * Maneja el evento de acción del botón de filtrar.
     *
     * @param evt El evento de acción asociado al botón de filtrar.
     */
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // Verificar si el campo de texto txtNombrePersona no está vacío
        String nombrePersona = txtNombrePersona.getText().trim();
        if (!nombrePersona.isEmpty()) {
            // Crear una lista para almacenar las personas que coincidan con el nombre
            List<ConsultarPersonaDTO> personasFiltradas = new ArrayList<>();

            // Recorrer la lista de personas y agregar las que coincidan con el nombre
            for (ConsultarPersonaDTO persona : personas) {
                String nombreCompleto = persona.getNombres().toLowerCase() + " " + persona.getApellidoPaterno().toLowerCase();
                if (nombreCompleto.contains(nombrePersona.toLowerCase())) {
                    personasFiltradas.add(persona);
                }
            }

            // Limpiar la tabla y luego actualizala con las personas filtradas
            limpiarTabla();
            actualizarTabla(personasFiltradas);
        } else if (dpFechaNacimiento.getDate() != null) {
            LocalDate fechaSeleccionada = dpFechaNacimiento.getDate();

            List<ConsultarPersonaDTO> personasFiltradas = new ArrayList<>();

            for (ConsultarPersonaDTO persona : personas) {
                Calendar fechaNacimiento = persona.getFechaNacimiento();
                LocalDate fechaNacimientoLocalDate = fechaNacimiento.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                if (fechaNacimientoLocalDate.isEqual(fechaSeleccionada)) {
                    personasFiltradas.add(persona);
                }
            }

            limpiarTabla();
            actualizarTabla(personasFiltradas);
        } else if (!txtRfc.getText().isEmpty()) {
            String rfc = txtRfc.getText().trim();

            List<ConsultarPersonaDTO> personasFiltradas = new ArrayList<>();

            for (ConsultarPersonaDTO persona : personas) {
                if (persona.getRfc().equalsIgnoreCase(rfc)) {
                    personasFiltradas.add(persona);
                }
            }
            
            limpiarTabla();
            actualizarTabla(personasFiltradas);
        } else {
            // Regresar a la tabla de personas si no hay nada seleccionado
            limpiarTabla();
            actualizarTabla(personas);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el label que refrencia un check para el campo "Fecha nacimiento".
     * 
     * @param evt El evento de acción que desencadena este método.
     */
    private void lblCheck2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCheck2MouseClicked
        // Si isChecked es false, establece la imagen de la palomita y cambia isChecked a true
        if (!isChecked) {
            lblCheck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPalomita.png")));
            isChecked = true;
            dpFechaNacimiento.setEnabled(true); // Habilita la edición cuando isChecked es true
        } else {
            // Si isChecked es true, establece una imagen vacía (o cualquier otra imagen deseada) y cambia isChecked a false
            lblCheck2.setIcon(null); // Esto eliminará la imagen actual
            isChecked = false;
            dpFechaNacimiento.setEnabled(false); // Deshabilita la edición cuando isChecked es false
            dpFechaNacimiento.setText("");
        }
    }//GEN-LAST:event_lblCheck2MouseClicked

    /**
     * Método que se ejecuta al hacer clic en el label que refrencia un check para el campo "Nombre de la persona".
     * 
     * @param evt El evento de acción que desencadena este método.
     */
    private void lblCheck1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCheck1MouseClicked
        // Si isChecked es false, establece la imagen de la palomita y cambia isChecked a true
        if (!isChecked) {
            lblCheck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPalomita.png")));
            isChecked = true;
            txtNombrePersona.setEnabled(true); // Habilita la edición cuando isChecked es true
        } else {
            // Si isChecked es true, establece una imagen vacía (o cualquier otra imagen deseada) y cambia isChecked a false
            lblCheck1.setIcon(null); // Esto eliminará la imagen actual
            isChecked = false;
            txtNombrePersona.setEnabled(false); // Deshabilita la edición cuando isChecked es false
            txtNombrePersona.setText("");
        }
    }//GEN-LAST:event_lblCheck1MouseClicked

    /**
     * Método que se ejecuta al hacer clic en el label que refrencia un check para el campo "RFC".
     * 
     * @param evt El evento de acción que desencadena este método.
     */
    private void lblCheck3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCheck3MouseClicked
        // Si isChecked es false, establece la imagen de la palomita y cambia isChecked a true
        if (!isChecked) {
            lblCheck3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPalomita.png")));
            isChecked = true;
            txtRfc.setEnabled(true); // Habilita la edición cuando isChecked es true
        } else {
            // Si isChecked es true, establece una imagen vacía (o cualquier otra imagen deseada) y cambia isChecked a false
            lblCheck3.setIcon(null); // Esto eliminará la imagen actual
            isChecked = false;
            txtRfc.setEnabled(false); // Deshabilita la edición cuando isChecked es false
            txtRfc.setText("");
        }

    }//GEN-LAST:event_lblCheck3MouseClicked

    /**
     * Método que se ejecuta al hacer clic en el botón "Volver".
     * 
     * @param evt El evento de acción que desencadena este método (en este caso, hacer clic en el botón "Volver").
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Seleccionar".
     * 
     * @param evt El evento de acción que desencadena este método (en este caso, hacer clic en el botón "Seleccionar).
     */
    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int filaSeleccionada = tblPersonas.getSelectedRow();

        if (filaSeleccionada != -1) { // Verificar si se ha seleccionado alguna fila
            Object[] datosFila = new Object[tblPersonas.getColumnCount()];

            for (int i = 0; i < tblPersonas.getColumnCount(); i++) {
                datosFila[i] = tblPersonas.getValueAt(filaSeleccionada, i);
            }
            
            // De la fila seleccionada toma el campo del rfc y se lo coloca a una personaDTO
            ConsultarPersonaDTO persona = new ConsultarPersonaDTO(datosFila[3].toString());
            // Con la personaDTO generada consultamos los tramites de la persona
            List<TramiteDTO> tramites = tramitesBO.consultarTramitesPersona(persona);
        
            ventana.cambiarVistaHistorialTramites(tramites);
        } else {
            // Si no se ha seleccionado ninguna fila, muestra un mensaje de advertencia o realiza alguna otra acción
            new Aviso().mostrarAviso(ventana, "Primero seleccione un tramite antes de generar el PDF");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloReportes;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnTramitesDisponibles;
    private javax.swing.JButton btnTramitesEnCurso;
    private javax.swing.JButton btnVolver;
    private com.github.lgooddatepicker.components.DatePicker dpFechaNacimiento;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCheck1;
    private javax.swing.JLabel lblCheck2;
    private javax.swing.JLabel lblCheck3;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblLogoInfo;
    private javax.swing.JLabel lblModuloConsultas;
    private javax.swing.JLabel lblNombrePersona;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTramitesDisponibles;
    private javax.swing.JLabel lblTramitesPendientes;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables

}
