package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.dtos.ConsultaPlacaDTO;
import java.text.SimpleDateFormat;

/**
 * Panel de confirmación de recepción de placa.
 * 
 * Esta clase representa una vista para mostrar la confirmación de la recepción 
 * de una placa tramitada.
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaConfirmacionRecepcion extends javax.swing.JPanel {

    private Ventana ventana;
    private ConsultaPlacaDTO placaConsultada; 
    
    /**
     * Constructor para mostrar la confirmación de trámite de placa nueva.
     *
     * @param ventana La ventana principal de la aplicación.
     * @param placaConsultaDTO Objeto ConsultaPlacaDTO que contiene la información de la consulta de placa tramitada.
     */
    public VistaConfirmacionRecepcion(Ventana ventana, ConsultaPlacaDTO placaConsultaDTO) {
        this.ventana = ventana;
        this.placaConsultada = placaConsultaDTO;
        initComponents();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        lblFechaEmision.setText(dateFormat.format(placaConsultaDTO.getFechaEmision().getTime()));
        lblFechaRecepcion.setText(dateFormat.format(placaConsultaDTO.getFechaRecepcion().getTime()));
        lblTipoTramite1.setText(placaConsultaDTO.getTipoVehiculo());
        lblNombreSolicitanteTramite1.setText(placaConsultaDTO.getPersona().getNombres()+" "+placaConsultaDTO.getPersona().getApellidoPaterno()+" "+placaConsultaDTO.getPersona().getApellidoMaterno());
        String costoFormateado = "$" + String.format("%.2f", placaConsultaDTO.getCosto())+" MXN";
        lblCostoTramite1.setText(costoFormateado + " MXN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar1 = new javax.swing.JButton();
        lblCostoTramite1 = new javax.swing.JLabel();
        lblNombreSolicitanteTramite1 = new javax.swing.JLabel();
        lblTipoTramite1 = new javax.swing.JLabel();
        lblFechaEmision = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        lblNombreSolicitante1 = new javax.swing.JLabel();
        lblTipo1 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblTramiteEnCurso1 = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblFechaRecepcion = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar1.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnAceptar1.setForeground(new java.awt.Color(253, 253, 253));
        btnAceptar1.setText("Aceptar");
        btnAceptar1.setBorder(null);
        btnAceptar1.setBorderPainted(false);
        btnAceptar1.setContentAreaFilled(false);
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 443, 142, 45));

        lblCostoTramite1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblCostoTramite1.setForeground(new java.awt.Color(196, 4, 67));
        add(lblCostoTramite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 350, 38));

        lblNombreSolicitanteTramite1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblNombreSolicitanteTramite1.setForeground(new java.awt.Color(196, 4, 67));
        add(lblNombreSolicitanteTramite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 450, 38));

        lblTipoTramite1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblTipoTramite1.setForeground(new java.awt.Color(196, 4, 67));
        add(lblTipoTramite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 318, 38));

        lblFechaEmision.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFechaEmision.setForeground(new java.awt.Color(196, 4, 67));
        add(lblFechaEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 500, 43));

        lblCosto1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblCosto1.setForeground(new java.awt.Color(196, 4, 67));
        lblCosto1.setText("Costo:");
        add(lblCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 91, 38));

        lblNombreSolicitante1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblNombreSolicitante1.setForeground(new java.awt.Color(215, 70, 118));
        lblNombreSolicitante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreSolicitante1.setText("<html>Nombre del<br>solicitante</html>");
        add(lblNombreSolicitante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 190, 76));

        lblTipo1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblTipo1.setForeground(new java.awt.Color(196, 4, 67));
        lblTipo1.setText("Tipo:");
        add(lblTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 72, 38));

        lblFecha1.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFecha1.setForeground(new java.awt.Color(196, 4, 67));
        lblFecha1.setText("Fecha emisión:");
        add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, 43));

        lblTramiteEnCurso1.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblTramiteEnCurso1.setForeground(new java.awt.Color(196, 4, 67));
        lblTramiteEnCurso1.setText("Entrega de placas realizada");
        add(lblTramiteEnCurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 460, 45));

        lblFecha2.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFecha2.setForeground(new java.awt.Color(196, 4, 67));
        lblFecha2.setText("Fecha recepción:");
        add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, 43));

        lblFechaRecepcion.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFechaRecepcion.setForeground(new java.awt.Color(196, 4, 67));
        add(lblFechaRecepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 500, 43));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaVentanaConfirmacionLicencia.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método cambia la vista actual de la aplicación a la vista de inicio o alguna otra vista predeterminada.
     * @param evt Evento de acción.
     */
    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnAceptar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCostoTramite1;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblFechaEmision;
    private javax.swing.JLabel lblFechaRecepcion;
    private javax.swing.JLabel lblNombreSolicitante1;
    private javax.swing.JLabel lblNombreSolicitanteTramite1;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblTipoTramite1;
    private javax.swing.JLabel lblTramiteEnCurso1;
    // End of variables declaration//GEN-END:variables
}
