package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.negocio.IPersonasBO;
import com.itson.bdavanzadas.negocio.PersonasBO;
import org.itson.bdavanzadas.conexion.Conexion;
import org.itson.bdavanzadas.conexion.IConexion;
import org.itson.bdavanzadas.daos.IPersonasDAO;
import org.itson.bdavanzadas.daos.PersonasDAO;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaConfirmacionTramiteLicencia extends javax.swing.JPanel {

    private Ventana ventana;
    private IConexion conexion = new Conexion();
    private IPersonasBO personasBO = new PersonasBO();

    /**
     * Constructor de la clase VistaInicio.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaConfirmacionTramiteLicencia(Ventana ventana) {
        this.ventana = ventana;
        this.personasBO = new PersonasBO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        lblCostoTramite = new javax.swing.JLabel();
        lblNombreSolicitanteTramite = new javax.swing.JLabel();
        lblTipoTramite = new javax.swing.JLabel();
        lblFechaTramite = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblNombreSolicitante = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTramiteEnCurso = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(253, 253, 253));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 443, 142, 45));

        lblCostoTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblCostoTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblCostoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 362, 225, 38));

        lblNombreSolicitanteTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblNombreSolicitanteTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblNombreSolicitanteTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 290, 450, 38));

        lblTipoTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblTipoTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 218, 318, 38));

        lblFechaTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFechaTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblFechaTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 163, 300, 43));

        lblCosto.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(196, 4, 67));
        lblCosto.setText("Costo:");
        add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 362, 91, 38));

        lblNombreSolicitante.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblNombreSolicitante.setForeground(new java.awt.Color(215, 70, 118));
        lblNombreSolicitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreSolicitante.setText("<html>Nombre del<br>solicitante</html>");
        add(lblNombreSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 271, 190, 76));

        lblTipo.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(196, 4, 67));
        lblTipo.setText("Tipo:");
        add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 218, 72, 38));

        lblFecha.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(196, 4, 67));
        lblFecha.setText("Fecha:");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 163, 100, 43));

        lblTramiteEnCurso.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblTramiteEnCurso.setForeground(new java.awt.Color(196, 4, 67));
        lblTramiteEnCurso.setText("Tramite en curso");
        add(lblTramiteEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 92, 290, 45));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaVentanaConfirmacionLicencia.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCostoTramite;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaTramite;
    private javax.swing.JLabel lblNombreSolicitante;
    private javax.swing.JLabel lblNombreSolicitanteTramite;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoTramite;
    private javax.swing.JLabel lblTramiteEnCurso;
    // End of variables declaration//GEN-END:variables

}
