package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.avisos.Aviso;
import com.itson.bdavanzadas.dtos.ConsultaPlacaDTO;
import com.itson.bdavanzadas.dtos.VehiculoNuevoDTO;
import com.itson.bdavanzadas.dtos.PlacaNuevaDTO;
import com.itson.bdavanzadas.negocio.IPlacasBO;
import com.itson.bdavanzadas.negocio.PlacasBO;

/**
 * Clase que representa la vista para los de la placa de un vehiculo a tramitar.
 * Esta clase muestra la información relacionada con el trámite de la placa y permite al usuario llevar a cabo dicho trámite.
 * La vista puede utilizarse tanto para tramitar una placa nueva como para consultar y tramitar una placa existente.
 * Además, muestra información sobre el costo del trámite y los detalles del vehículo asociado a la placa.
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaTramitarPlaca extends javax.swing.JPanel {
    private Ventana ventana;
    private VehiculoNuevoDTO autoDTO;
    private PlacaNuevaDTO placaNuevaDTO;
    private ConsultaPlacaDTO placaConsultadaDTO;
    private IPlacasBO placasBO;


    /**
     * Constructor de la clase VistaTramitarPlaca para tramitar una placa nueva.
     * 
     * @param ventana La ventana principal de la aplicación.
     * @param placaDTO El DTO de la placa a tramitar.
     */
    public VistaTramitarPlaca(Ventana ventana, PlacaNuevaDTO placaDTO) {
        this.ventana = ventana;
        this.placaNuevaDTO = placaDTO;
        this.placasBO = new PlacasBO();
        initComponents();
        cargarDatos();
    }
    
    /**
     * Constructor de la clase VistaTramitarPlaca para tramitar una placa nueva.
     * 
     * @param ventana La ventana principal de la aplicación.
     * @param placaDTO El DTO de la placa a tramitar.
     */
    public VistaTramitarPlaca(Ventana ventana, ConsultaPlacaDTO placaDTO) {
        this.ventana = ventana;
        this.placaConsultadaDTO = placaDTO;
        this.placasBO = new PlacasBO();
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramitesDisponibles = new javax.swing.JButton();
        btnTramitesEnCurso = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        btnModuloReportes = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoInfo = new javax.swing.JLabel();
        lblTramitesDisponibles = new javax.swing.JLabel();
        lblTramitesPendientes = new javax.swing.JLabel();
        lblModuloConsultas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        lblNumeroPlacaInfo = new javax.swing.JLabel();
        lblNumeroSerieInfo = new javax.swing.JLabel();
        lblMarcaInfo = new javax.swing.JLabel();
        lblLineaInfo = new javax.swing.JLabel();
        lblModeloInfo = new javax.swing.JLabel();
        lblTipoInfo = new javax.swing.JLabel();
        lblColorInfo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        lblNumeroPlaca = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnTramitar = new javax.swing.JButton();
        lblCostoLicencias = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        lblOpcion1 = new javax.swing.JLabel();
        lblOpcion2 = new javax.swing.JLabel();
        lblCostoNormal = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        lblCosto2 = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCostoInfo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitesDisponibles.setBorder(null);
        btnTramitesDisponibles.setBorderPainted(false);
        btnTramitesDisponibles.setContentAreaFilled(false);
        btnTramitesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesDisponiblesActionPerformed(evt);
            }
        });
        add(btnTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 128, 40));

        btnTramitesEnCurso.setBorder(null);
        btnTramitesEnCurso.setBorderPainted(false);
        btnTramitesEnCurso.setContentAreaFilled(false);
        btnTramitesEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesEnCursoActionPerformed(evt);
            }
        });
        add(btnTramitesEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 128, 40));

        btnModuloConsultas.setBorder(null);
        btnModuloConsultas.setBorderPainted(false);
        btnModuloConsultas.setContentAreaFilled(false);
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 128, 40));

        btnModuloReportes.setBorder(null);
        btnModuloReportes.setBorderPainted(false);
        btnModuloReportes.setContentAreaFilled(false);
        btnModuloReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloReportesActionPerformed(evt);
            }
        });
        add(btnModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 128, 40));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(196, 4, 67));
        lblTitulo.setText("Información trámite placa");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 120, 450, 43));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSol.png"))); // NOI18N
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 60, 60));

        lblLogoInfo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblLogoInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoInfo.setText("Agencia del Sol");
        add(lblLogoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 16, 260, 43));

        lblTramitesDisponibles.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesDisponibles.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesDisponibles.setText("<html>Trámites<br>disponibles</html>");
        add(lblTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 105, 87, 34));

        lblTramitesPendientes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesPendientes.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesPendientes.setText("<html>Trámites<br>en curso</html>");
        add(lblTramitesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 160, 87, 34));

        lblModuloConsultas.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblModuloConsultas.setForeground(new java.awt.Color(196, 4, 67));
        lblModuloConsultas.setText("<html>Modulo<br>consultas</html>");
        add(lblModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 215, 87, 34));

        lblReportes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(196, 4, 67));
        lblReportes.setText("<html>Modulo<br>reportes</html>");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 270, 87, 34));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramiteDisponibles.png"))); // NOI18N
        add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 40, 40));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramitesEnCurso.png"))); // NOI18N
        add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 40, 40));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConsultas.png"))); // NOI18N
        add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 40, 40));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReporte.png"))); // NOI18N
        add(lblLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 40, 40));

        lblNumeroPlacaInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblNumeroPlacaInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblNumeroPlacaInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeroPlacaInfo.setText("Número de placa:");
        add(lblNumeroPlacaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 185, 155, 24));

        lblNumeroSerieInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblNumeroSerieInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblNumeroSerieInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeroSerieInfo.setText("Número de serie:");
        add(lblNumeroSerieInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 215, 155, 24));

        lblMarcaInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblMarcaInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblMarcaInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMarcaInfo.setText("Marca:");
        add(lblMarcaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 245, 155, 24));

        lblLineaInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblLineaInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblLineaInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLineaInfo.setText("Linea:");
        add(lblLineaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 274, 155, 24));

        lblModeloInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblModeloInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblModeloInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloInfo.setText("Modelo:");
        add(lblModeloInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 305, 155, 24));

        lblTipoInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblTipoInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblTipoInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoInfo.setText("Tipo:");
        add(lblTipoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 365, 155, 24));

        lblColorInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblColorInfo.setForeground(new java.awt.Color(215, 70, 118));
        lblColorInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColorInfo.setText("Color:");
        add(lblColorInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 335, 155, 24));

        lblTipo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(215, 70, 118));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipo.setText("Tipo:");
        add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 365, 190, 24));

        lblColor.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblColor.setForeground(new java.awt.Color(215, 70, 118));
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblColor.setText("Color:");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 335, 380, 24));

        lblModelo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(215, 70, 118));
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModelo.setText("Modelo:");
        add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 305, 380, 24));

        lblLinea.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(215, 70, 118));
        lblLinea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLinea.setText("Linea:");
        add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 274, 380, 24));

        lblMarca.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(215, 70, 118));
        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMarca.setText("Marca:");
        add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 245, 380, 24));

        lblNumeroSerie.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblNumeroSerie.setForeground(new java.awt.Color(215, 70, 118));
        lblNumeroSerie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumeroSerie.setText("Número de serie:");
        add(lblNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 215, 380, 24));

        lblNumeroPlaca.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblNumeroPlaca.setForeground(new java.awt.Color(215, 70, 118));
        lblNumeroPlaca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumeroPlaca.setText("Número de placa:");
        add(lblNumeroPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 185, 380, 24));

        btnVolver.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(253, 253, 253));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 416, 142, 45));

        btnTramitar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnTramitar.setForeground(new java.awt.Color(253, 253, 253));
        btnTramitar.setText("Tramitar");
        btnTramitar.setBorder(null);
        btnTramitar.setContentAreaFilled(false);
        btnTramitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitarActionPerformed(evt);
            }
        });
        add(btnTramitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 418, 142, 45));

        lblCostoLicencias.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblCostoLicencias.setForeground(new java.awt.Color(196, 4, 67));
        lblCostoLicencias.setText("Costo de placas");
        add(lblCostoLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 399, 180, 29));

        lblVigencia.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblVigencia.setForeground(new java.awt.Color(34, 33, 33));
        lblVigencia.setText("Trámite");
        add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 65, 22));

        lblOpcion1.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblOpcion1.setForeground(new java.awt.Color(34, 33, 33));
        lblOpcion1.setText("Automóvil nuevo");
        add(lblOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 475, 160, 20));

        lblOpcion2.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblOpcion2.setForeground(new java.awt.Color(34, 33, 33));
        lblOpcion2.setText("Automóvil usado");
        add(lblOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 495, 160, 20));

        lblCostoNormal.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoNormal.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoNormal.setText("Costo normal");
        add(lblCostoNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 100, 22));

        lblCosto1.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCosto1.setForeground(new java.awt.Color(34, 33, 33));
        lblCosto1.setText("$1,500.00 MXN");
        add(lblCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 475, 200, 20));

        lblCosto2.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCosto2.setForeground(new java.awt.Color(34, 33, 33));
        lblCosto2.setText("$1,000.00 MXN");
        add(lblCosto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 495, 200, 20));

        lblCosto.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(196, 4, 67));
        lblCosto.setText("$1,000.00 MXN");
        add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 290, 29));

        lblCostoInfo.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblCostoInfo.setForeground(new java.awt.Color(196, 4, 67));
        lblCostoInfo.setText("Costo:");
        add(lblCostoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 70, 29));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaPlacaTramitar.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites en curso".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites en curso").
     */
    private void btnTramitesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesDisponiblesActionPerformed
    }//GEN-LAST:event_btnTramitesDisponiblesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites disponibles".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites disponibles").
     */
    private void btnTramitesEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesEnCursoActionPerformed
        ventana.cambiarVistaTramitesEnCurso();
    }//GEN-LAST:event_btnTramitesEnCursoActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo consultas".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo consultas").
     */
    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed
        ventana.cambiarVistaModuloConsultas();
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo reportes".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo reportes").
     */
    private void btnModuloReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloReportesActionPerformed
        ventana.cambiarVistaModuloReporte();
    }//GEN-LAST:event_btnModuloReportesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Tramitar".
     * Este método realiza el trámite de la placa y actualiza la base de datos si el usuario confirma.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if(ventana.isPlacaNueva()){
            ventana.cambiarVistaAgregarVehiculo(placaNuevaDTO.getPersona());
        }else{
            ventana.cambiarVistaVehiculoTramitar(placaConsultadaDTO.getPersona());
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Tramitar".
     * Este método realiza el trámite de la placa y actualiza la base de datos si el usuario confirma.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnTramitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitarActionPerformed
        if (new Aviso().mostrarConfirmacion(ventana, "¿Seguro de querer tramitar la placa?", "¿Quiére una nueva placa?")) {
            if(ventana.isPlacaNueva()){
                placasBO.realizarTramitePlaca(placaNuevaDTO);
                ventana.cambiarVistaConfirmacionTramite(placaNuevaDTO);
            }else{
                placasBO.realizarTramitePlaca(placaConsultadaDTO);
                ventana.cambiarVistaConfirmacionTramite(placaConsultadaDTO);
            }
        }
    }//GEN-LAST:event_btnTramitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloReportes;
    private javax.swing.JButton btnTramitar;
    private javax.swing.JButton btnTramitesDisponibles;
    private javax.swing.JButton btnTramitesEnCurso;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorInfo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCosto2;
    private javax.swing.JLabel lblCostoInfo;
    private javax.swing.JLabel lblCostoLicencias;
    private javax.swing.JLabel lblCostoNormal;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblLineaInfo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblLogoInfo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarcaInfo;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModeloInfo;
    private javax.swing.JLabel lblModuloConsultas;
    private javax.swing.JLabel lblNumeroPlaca;
    private javax.swing.JLabel lblNumeroPlacaInfo;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblNumeroSerieInfo;
    private javax.swing.JLabel lblOpcion1;
    private javax.swing.JLabel lblOpcion2;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoInfo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTramitesDisponibles;
    private javax.swing.JLabel lblTramitesPendientes;
    private javax.swing.JLabel lblVigencia;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para cargar los datos de la placa y el vehículo asociado a la interfaz gráfica.
     * Este método se llama al inicializar la vista y muestra los detalles de la placa y el vehículo en los campos correspondientes.
     */
    private void cargarDatos() {
        String tipoVehiculo;
        String numeroPlaca = placasBO.generaPlacaNueva();
        // Dependiendo del tipo de dto se asigna la variable correspondie los valores.
        if(ventana.isPlacaNueva()){
            lblTipo.setText("Nuevo");
            placasBO.calcularCostoVehiculoNuevo(placaNuevaDTO);
            placaNuevaDTO.setNumero(numeroPlaca);
            autoDTO = placaNuevaDTO.getVehiculo();
            lblNumeroPlaca.setText(placaNuevaDTO.getNumero());
            tipoVehiculo = placaNuevaDTO.getTipoVehiculo();
        }else{
            lblTipo.setText("Usado");
            placasBO.calcularCostoVehiculoUsado(placaConsultadaDTO);
            placaConsultadaDTO.setNumero(numeroPlaca);
            autoDTO = placaConsultadaDTO.getVehiculo();
            lblNumeroPlaca.setText(placaConsultadaDTO.getNumero());
            tipoVehiculo = placaConsultadaDTO.getTipoVehiculo();
        }
        
        lblColor.setText(autoDTO.getColor());
        lblLinea.setText(autoDTO.getLinea());
        lblModelo.setText(autoDTO.getModelo());
        lblMarca.setText(autoDTO.getMarca());
        lblNumeroSerie.setText(autoDTO.getNumeroSerie());
        
        String numeroFormateado = String.format("%.2f", 1000F);
        lblCosto.setText("$" + numeroFormateado + " MXN");
        
        switch(tipoVehiculo){
            case "Automovil":
                lblOpcion1.setText("Automóvil nuevo");
                lblOpcion2.setText("Automóvil usado");
                lblCosto1.setText("$1,500.00 MXN");
                lblCosto2.setText("$1,000.00 MXN");
                break;
        }
    }

}
