package org.itson.bdavanzadas.agenciadelsol;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaAgregarVehiculo extends javax.swing.JPanel {

    private  Ventana ventana;
    
    /**
     * Constructor de la clase VistaInicio.
     * 
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaAgregarVehiculo(Ventana ventana) {
        this.ventana = ventana;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramitesDisponibles = new javax.swing.JButton();
        btnTramitesEnCurso = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        btnModuloReportes = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoInfo = new javax.swing.JLabel();
        lblTramitesDisponibles = new javax.swing.JLabel();
        lblTramitesPendientes = new javax.swing.JLabel();
        lblModuloConsultas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblLinea = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitesDisponibles.setBorder(null);
        btnTramitesDisponibles.setBorderPainted(false);
        btnTramitesDisponibles.setContentAreaFilled(false);
        btnTramitesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesDisponiblesActionPerformed(evt);
            }
        });
        add(btnTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 128, 40));

        btnTramitesEnCurso.setBorder(null);
        btnTramitesEnCurso.setBorderPainted(false);
        btnTramitesEnCurso.setContentAreaFilled(false);
        btnTramitesEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesEnCursoActionPerformed(evt);
            }
        });
        add(btnTramitesEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 128, 40));

        btnModuloConsultas.setBorder(null);
        btnModuloConsultas.setBorderPainted(false);
        btnModuloConsultas.setContentAreaFilled(false);
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 128, 40));

        btnModuloReportes.setBorder(null);
        btnModuloReportes.setBorderPainted(false);
        btnModuloReportes.setContentAreaFilled(false);
        btnModuloReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloReportesActionPerformed(evt);
            }
        });
        add(btnModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 128, 40));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(196, 4, 67));
        lblTitulo.setText("Agregar Vehículo");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSol.png"))); // NOI18N
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 60, 60));

        lblLogoInfo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblLogoInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoInfo.setText("Agencia del Sol");
        add(lblLogoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 16, 260, 43));

        lblTramitesDisponibles.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesDisponibles.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesDisponibles.setText("<html>Trámites<br>disponibles</html>");
        add(lblTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 105, 87, 34));

        lblTramitesPendientes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesPendientes.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesPendientes.setText("<html>Trámites<br>en curso</html>");
        add(lblTramitesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 160, 87, 34));

        lblModuloConsultas.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblModuloConsultas.setForeground(new java.awt.Color(196, 4, 67));
        lblModuloConsultas.setText("<html>Modulo<br>consultas</html>");
        add(lblModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 215, 87, 34));

        lblReportes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(196, 4, 67));
        lblReportes.setText("<html>Modulo<br>reportes</html>");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 270, 87, 34));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramiteDisponibles.png"))); // NOI18N
        add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 40, 40));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramitesEnCurso.png"))); // NOI18N
        add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 40, 40));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConsultas.png"))); // NOI18N
        add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 40, 40));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReporte.png"))); // NOI18N
        add(lblLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 40, 40));

        lblNumeroSerie.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblNumeroSerie.setForeground(new java.awt.Color(215, 70, 118));
        lblNumeroSerie.setText("Número de serie:");
        add(lblNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 190, -1, 24));

        txtNumeroSerie.setBackground(new java.awt.Color(247, 242, 244));
        txtNumeroSerie.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtNumeroSerie.setForeground(new java.awt.Color(143, 143, 143));
        txtNumeroSerie.setBorder(null);
        add(txtNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 223, 352, 34));

        lblMarca.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(215, 70, 118));
        lblMarca.setText("Marca:");
        add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 275, -1, 24));

        txtMarca.setBackground(new java.awt.Color(247, 242, 244));
        txtMarca.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(143, 143, 143));
        txtMarca.setBorder(null);
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 308, 352, 34));

        lblLinea.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(215, 70, 118));
        lblLinea.setText("Línea:");
        add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 274, -1, 24));

        txtLinea.setBackground(new java.awt.Color(247, 242, 244));
        txtLinea.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtLinea.setForeground(new java.awt.Color(143, 143, 143));
        txtLinea.setBorder(null);
        txtLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineaActionPerformed(evt);
            }
        });
        add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 308, 352, 34));

        lblModelo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(215, 70, 118));
        lblModelo.setText("Modelo:");
        add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 360, -1, 24));

        txtModelo.setBackground(new java.awt.Color(247, 242, 244));
        txtModelo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(143, 143, 143));
        txtModelo.setBorder(null);
        add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 393, 352, 34));

        lblColor.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblColor.setForeground(new java.awt.Color(215, 70, 118));
        lblColor.setText("Color:");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, 24));

        txtColor.setBackground(new java.awt.Color(247, 242, 244));
        txtColor.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtColor.setForeground(new java.awt.Color(143, 143, 143));
        txtColor.setBorder(null);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 393, 352, 34));

        lblTipo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(215, 70, 118));
        lblTipo.setText("Línea:");
        add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 24));

        cbxTipo.setBackground(new java.awt.Color(247, 242, 244));
        cbxTipo.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        cbxTipo.setForeground(new java.awt.Color(157, 134, 90));
        cbxTipo.setFocusable(false);
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });
        add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 360, 40));

        btnVolver.setBackground(new java.awt.Color(143, 143, 143));
        btnVolver.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(253, 253, 253));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 465, 142, 45));

        btnVolver1.setBackground(new java.awt.Color(215, 70, 118));
        btnVolver1.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(253, 253, 253));
        btnVolver1.setText("Agregar");
        btnVolver1.setBorderPainted(false);
        add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 465, 142, 45));

        fondo.setBackground(new java.awt.Color(102, 102, 102));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaAgregarVehiculo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites en curso".
     * 
     * @param evt El evento de acción que desencadena este método (en este caso, hacer clic en el botón "Trámites en curso").
     */
    private void btnTramitesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesDisponiblesActionPerformed
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnTramitesDisponiblesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites disponibles".
     * 
     * @param evt El evento de acción que desencadena este método (en este caso, hacer clic en el botón "Trámites disponibles").
     */
    private void btnTramitesEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesEnCursoActionPerformed
        ventana.cambiarVistaTramitesEnCurso();
    }//GEN-LAST:event_btnTramitesEnCursoActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo consultas".
     * 
     * @param evt El evento de acción que desencadena este método (en este caso, hacer clic en el botón "Módulo consultas").
     */
    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed
        ventana.cambiarVistaModuloConsultas();
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo reportes".
     * 
     * @param evt El evento de acción que desencadena este método (en este caso, hacer clic en el botón "Módulo reportes").
     */
    private void btnModuloReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloReportesActionPerformed
        ventana.cambiarVistaModuloReporte();
    }//GEN-LAST:event_btnModuloReportesActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void txtLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloReportes;
    private javax.swing.JButton btnTramitesDisponibles;
    private javax.swing.JButton btnTramitesEnCurso;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblLogoInfo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModuloConsultas;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTramitesDisponibles;
    private javax.swing.JLabel lblTramitesPendientes;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumeroSerie;
    // End of variables declaration//GEN-END:variables

}
