package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.dtos.ConsultarPersonaDTO;
import com.itson.bdavanzadas.dtos.LicenciasDTO;
import com.itson.bdavanzadas.negocio.ILicenciaBO;
import com.itson.bdavanzadas.negocio.IPersonasBO;
import com.itson.bdavanzadas.negocio.LicenciaBO;
import com.itson.bdavanzadas.negocio.PersonasBO;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.itson.bdavanzadas.daos.IPersonasDAO;
import org.itson.bdavanzadas.daos.PersonasDAO;
import org.itson.bdavanzadas.entidades.Discapacidad;
import org.itson.bdavanzadas.entidades.EstadoLicencia;
import org.itson.bdavanzadas.entidades.Persona;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaTramitarLicencia extends javax.swing.JPanel {

    private Ventana ventana;
    private IPersonasBO personasBO;
    private ILicenciaBO licenciasBO;
    private ConsultarPersonaDTO personaDTO;
    
    /**
     * Constructor de la clase VistaPersonaATramitar.
     *
     * @param ventana La ventana de Persona a tramitar recibe datos para
     * consultar personas.
     */
    public VistaTramitarLicencia(Ventana ventana, ConsultarPersonaDTO personaDTO) {
        this.ventana = ventana;
        this.personasBO = new PersonasBO();
//        this.licenciasBO = new LicenciaBO(licenciasDAO, personasBO)
        this.personaDTO = personaDTO;
        initComponents();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramitesDisponibles = new javax.swing.JButton();
        btnTramitesEnCurso = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        btnModuloReportes = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoInfo = new javax.swing.JLabel();
        lblTramitesDisponibles = new javax.swing.JLabel();
        lblTramitesPendientes = new javax.swing.JLabel();
        lblModuloConsultas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        lblCurpPersona = new javax.swing.JLabel();
        cbxAnioVigencia = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnTramitar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCostoLicencias = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        lblVigencia1 = new javax.swing.JLabel();
        lblVigencia2 = new javax.swing.JLabel();
        lblVigencia3 = new javax.swing.JLabel();
        lblCostoNormal = new javax.swing.JLabel();
        lblCostoNormal1 = new javax.swing.JLabel();
        lblCostoNormal2 = new javax.swing.JLabel();
        lblCostoNormal3 = new javax.swing.JLabel();
        lblCostoDiscapacitado = new javax.swing.JLabel();
        lblCostoDiscapacitado1 = new javax.swing.JLabel();
        lblCostoDiscapacitado2 = new javax.swing.JLabel();
        lblCostoDiscapacitado3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitesDisponibles.setBorder(null);
        btnTramitesDisponibles.setBorderPainted(false);
        btnTramitesDisponibles.setContentAreaFilled(false);
        btnTramitesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesDisponiblesActionPerformed(evt);
            }
        });
        add(btnTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 128, 40));

        btnTramitesEnCurso.setBorder(null);
        btnTramitesEnCurso.setBorderPainted(false);
        btnTramitesEnCurso.setContentAreaFilled(false);
        btnTramitesEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesEnCursoActionPerformed(evt);
            }
        });
        add(btnTramitesEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 128, 40));

        btnModuloConsultas.setBorder(null);
        btnModuloConsultas.setBorderPainted(false);
        btnModuloConsultas.setContentAreaFilled(false);
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 128, 40));

        btnModuloReportes.setBorder(null);
        btnModuloReportes.setBorderPainted(false);
        btnModuloReportes.setContentAreaFilled(false);
        btnModuloReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloReportesActionPerformed(evt);
            }
        });
        add(btnModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 128, 40));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(196, 4, 67));
        lblTitulo.setText("Persona a tramitar");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 120, 340, 43));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSol.png"))); // NOI18N
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 60, 60));

        lblLogoInfo.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblLogoInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoInfo.setText("Agencia del Sol");
        add(lblLogoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 16, 260, 43));

        lblTramitesDisponibles.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesDisponibles.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesDisponibles.setText("<html>Trámites<br>disponibles</html>");
        add(lblTramitesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 105, 87, 34));

        lblTramitesPendientes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblTramitesPendientes.setForeground(new java.awt.Color(196, 4, 67));
        lblTramitesPendientes.setText("<html>Trámites<br>en curso</html>");
        add(lblTramitesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 160, 87, 34));

        lblModuloConsultas.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblModuloConsultas.setForeground(new java.awt.Color(196, 4, 67));
        lblModuloConsultas.setText("<html>Modulo<br>consultas</html>");
        add(lblModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 215, 87, 34));

        lblReportes.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(196, 4, 67));
        lblReportes.setText("<html>Modulo<br>reportes</html>");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 270, 87, 34));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramiteDisponibles.png"))); // NOI18N
        add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 40, 40));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tramitesEnCurso.png"))); // NOI18N
        add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, 40, 40));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConsultas.png"))); // NOI18N
        add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, 40, 40));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReporte.png"))); // NOI18N
        add(lblLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, 40, 40));

        lblCurpPersona.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblCurpPersona.setForeground(new java.awt.Color(215, 70, 118));
        lblCurpPersona.setText("Años de vigencia:");
        add(lblCurpPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 179, 215, 30));

        cbxAnioVigencia.setBackground(new java.awt.Color(247, 242, 244));
        cbxAnioVigencia.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        cbxAnioVigencia.setForeground(new java.awt.Color(157, 134, 90));
        cbxAnioVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 AÑO", "2 AÑOS", "3 AÑOS" }));
        cbxAnioVigencia.setSelectedIndex(-1);
        cbxAnioVigencia.setFocusable(false);
        cbxAnioVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAnioVigenciaActionPerformed(evt);
            }
        });
        add(cbxAnioVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 210, 460, 40));

        btnVolver.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(253, 253, 253));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 334, 142, 45));

        btnTramitar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnTramitar.setForeground(new java.awt.Color(253, 253, 253));
        btnTramitar.setText("Tramitar");
        btnTramitar.setBorder(null);
        btnTramitar.setContentAreaFilled(false);
        btnTramitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitarActionPerformed(evt);
            }
        });
        add(btnTramitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 334, 142, 45));

        lblPrecio.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(215, 70, 118));
        lblPrecio.setText("Precio:");
        add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 60, 32));

        lblCosto.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(215, 70, 118));
        lblCosto.setText("$0.0 MXN");
        add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 360, 32));

        lblCostoLicencias.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblCostoLicencias.setForeground(new java.awt.Color(215, 70, 118));
        lblCostoLicencias.setText("Costo de licencias");
        add(lblCostoLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 399, 210, 40));

        lblVigencia.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblVigencia.setForeground(new java.awt.Color(34, 33, 33));
        lblVigencia.setText("Vigencia");
        add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 65, 22));

        lblVigencia1.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblVigencia1.setForeground(new java.awt.Color(34, 33, 33));
        lblVigencia1.setText("1 año");
        add(lblVigencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 475, 50, 20));

        lblVigencia2.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblVigencia2.setForeground(new java.awt.Color(34, 33, 33));
        lblVigencia2.setText("2 años");
        add(lblVigencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 495, 50, 20));

        lblVigencia3.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblVigencia3.setForeground(new java.awt.Color(34, 33, 33));
        lblVigencia3.setText("3 años");
        add(lblVigencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 515, 50, 20));

        lblCostoNormal.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoNormal.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoNormal.setText("Costo normal");
        add(lblCostoNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, 22));

        lblCostoNormal1.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoNormal1.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoNormal1.setText("$1100.00 MXN");
        add(lblCostoNormal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 515, 110, 22));

        lblCostoNormal2.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoNormal2.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoNormal2.setText("$600.00 MXN");
        add(lblCostoNormal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 475, 110, 22));

        lblCostoNormal3.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoNormal3.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoNormal3.setText("$900.00 MXN");
        add(lblCostoNormal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 495, 110, 22));

        lblCostoDiscapacitado.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoDiscapacitado.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoDiscapacitado.setText("Costo discapacitado");
        add(lblCostoDiscapacitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 150, 22));

        lblCostoDiscapacitado1.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoDiscapacitado1.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoDiscapacitado1.setText("$200.00 MXN");
        add(lblCostoDiscapacitado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 475, 110, 22));

        lblCostoDiscapacitado2.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoDiscapacitado2.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoDiscapacitado2.setText("$500.00 MXN");
        add(lblCostoDiscapacitado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 495, 110, 22));

        lblCostoDiscapacitado3.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblCostoDiscapacitado3.setForeground(new java.awt.Color(34, 33, 33));
        lblCostoDiscapacitado3.setText("$700.00 MXN");
        add(lblCostoDiscapacitado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 515, 110, 22));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanaLicencias.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites en curso".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites en curso").
     */
    private void btnTramitesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesDisponiblesActionPerformed
    }//GEN-LAST:event_btnTramitesDisponiblesActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Trámites disponibles".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Trámites disponibles").
     */
    private void btnTramitesEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesEnCursoActionPerformed
        ventana.cambiarVistaTramitesEnCurso();
    }//GEN-LAST:event_btnTramitesEnCursoActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo consultas".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo consultas").
     */
    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed
        ventana.cambiarVistaModuloConsultas();
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Módulo reportes".
     *
     * @param evt El evento de acción que desencadena este método (en este caso,
     * hacer clic en el botón "Módulo reportes").
     */
    private void btnModuloReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloReportesActionPerformed
        ventana.cambiarVistaModuloReporte();
    }//GEN-LAST:event_btnModuloReportesActionPerformed

    private void cbxAnioVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAnioVigenciaActionPerformed
        int seleccion = cbxAnioVigencia.getSelectedIndex();
        if(personaDTO.getDiscapacidad() == Discapacidad.NORMAL){
            switch (seleccion) {
                case 0:
                    lblCosto.setText("$600.00 MXN");
                    break;
                case 1:
                    lblCosto.setText("$900.00 MXN");
                    break;
                default:
                    lblCosto.setText("$1,100.00 MXN");
            }
        }else{
            switch (seleccion) {
                case 0:
                    lblCosto.setText("$200.00 MXN");
                    break;
                case 1:
                    lblCosto.setText("$500.00 MXN");
                    break;
                default:
                    lblCosto.setText("$700.00 MXN");
            }
        }
    }//GEN-LAST:event_cbxAnioVigenciaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventana.cambiarVistaPersonaATramitar();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnTramitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitarActionPerformed
        int seleccion = cbxAnioVigencia.getSelectedIndex();
        Integer años = cbxAnioVigencia.getSelectedIndex();
        float costo = 0F;
        
        if(personaDTO.getDiscapacidad() == Discapacidad.NORMAL){
            switch (seleccion) {
                case 0:
                    costo = 600F;
                    break;
                case 1:
                    costo = 900F;
                    break;
                default:
                    costo = 1100F;
            }
        }else{
            switch (seleccion) {
                case 0:
                    costo = 200F;
                    break;
                case 1:
                    costo = 500F;
                    break;
                default:
                    costo = 700F;
            }
        }
        
        
        Calendar fechaEmision = Calendar.getInstance();
        Calendar fechaVigencia = (Calendar) fechaEmision.clone();
        fechaVigencia.add(Calendar.YEAR, años);
        
        ConsultarPersonaDTO personaConsultada = personasBO.consultarPersonaPorRfc(personaDTO);
        Persona persona = new Persona(
                personaConsultada.getNombres(), 
                personaConsultada.getApellidoPaterno(), 
                personaConsultada.getApellidoMaterno(), 
                personaConsultada.getTelefono(), 
                personaConsultada.getTelefono(), 
                personaConsultada.getFechaNacimiento(), 
                personaConsultada.getDiscapacidad()
        );

        LicenciasDTO licenciaDTO = new LicenciasDTO(
                EstadoLicencia.ACTIVA, 
                fechaVigencia, 
                fechaEmision, 
                costo, 
                persona);
        licenciasBO.realizarTramite(licenciaDTO);
    }//GEN-LAST:event_btnTramitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloReportes;
    private javax.swing.JButton btnTramitar;
    private javax.swing.JButton btnTramitesDisponibles;
    private javax.swing.JButton btnTramitesEnCurso;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxAnioVigencia;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCostoDiscapacitado;
    private javax.swing.JLabel lblCostoDiscapacitado1;
    private javax.swing.JLabel lblCostoDiscapacitado2;
    private javax.swing.JLabel lblCostoDiscapacitado3;
    private javax.swing.JLabel lblCostoLicencias;
    private javax.swing.JLabel lblCostoNormal;
    private javax.swing.JLabel lblCostoNormal1;
    private javax.swing.JLabel lblCostoNormal2;
    private javax.swing.JLabel lblCostoNormal3;
    private javax.swing.JLabel lblCurpPersona;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblLogoInfo;
    private javax.swing.JLabel lblModuloConsultas;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTramitesDisponibles;
    private javax.swing.JLabel lblTramitesPendientes;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JLabel lblVigencia1;
    private javax.swing.JLabel lblVigencia2;
    private javax.swing.JLabel lblVigencia3;
    // End of variables declaration//GEN-END:variables

}
