package org.itson.bdavanzadas.agenciadelsol;

import com.itson.bdavanzadas.dtos.ConsultaPlacaDTO;
import com.itson.bdavanzadas.dtos.LicenciasDTO;
import com.itson.bdavanzadas.dtos.PlacaNuevaDTO;
import com.itson.bdavanzadas.negocio.IPersonasBO;
import com.itson.bdavanzadas.negocio.PersonasBO;
import java.text.SimpleDateFormat;
import org.itson.bdavanzadas.conexion.Conexion;
import org.itson.bdavanzadas.conexion.IConexion;


/**
 * Clase que representa la vista de confirmación de trámite.
 * Esta vista muestra la confirmación de un trámite, ya sea para una licencia,
 * una placa de un vehiculo nuevo o uno usado.
 * 
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 247887
 */
public class VistaConfirmacionTramite extends javax.swing.JPanel {

    private Ventana ventana;
    private IConexion conexion = new Conexion();
    private IPersonasBO personasBO = new PersonasBO();
    private LicenciasDTO licenciaDTO;
    private PlacaNuevaDTO placaNuevaDTO;
    private ConsultaPlacaDTO placaConsultaDTO;

    /**
     * Constructor para mostrar la confirmación de trámite de licencia.
     *
     * @param ventana La ventana principal de la aplicación.
     * @param licenciaDTO Objeto LicenciasDTO que contiene la información de la licencia tramitada.
     */
    public VistaConfirmacionTramite(Ventana ventana, LicenciasDTO licenciaDTO) {
        this.ventana = ventana;
        this.personasBO = new PersonasBO();
        this.licenciaDTO = licenciaDTO;
        initComponents();
        cargarDatosLicencia();
    }
    
    /**
     * Constructor para mostrar la confirmación de trámite de placa nueva.
     *
     * @param ventana La ventana principal de la aplicación.
     * @param placaNuevaDTO Objeto PlacaNuevaDTO que contiene la información de la placa nueva tramitada.
     */
    public VistaConfirmacionTramite(Ventana ventana, PlacaNuevaDTO placaNuevaDTO) {
        this.ventana = ventana;
        this.personasBO = new PersonasBO();
        this.placaNuevaDTO = placaNuevaDTO;
        initComponents();
        cargarDatosPlacaNueva();
    }
    
     /**
     * Constructor para mostrar la confirmación de trámite de placa nueva.
     *
     * @param ventana La ventana principal de la aplicación.
     * @param placaConsultaDTO Objeto ConsultaPlacaDTO que contiene la información de la consulta de placa tramitada.
     */
    public VistaConfirmacionTramite(Ventana ventana, ConsultaPlacaDTO placaConsultaDTO) {
        this.ventana = ventana;
        this.personasBO = new PersonasBO();
        this.placaConsultaDTO = placaConsultaDTO;
        initComponents();
        cargarDatosPlacaRenovada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        lblCostoTramite = new javax.swing.JLabel();
        lblNombreSolicitanteTramite = new javax.swing.JLabel();
        lblTipoTramite = new javax.swing.JLabel();
        lblFechaTramite = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblNombreSolicitante = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTramiteEnCurso = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 242, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(253, 253, 253));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 443, 142, 45));

        lblCostoTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblCostoTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblCostoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 362, 350, 38));

        lblNombreSolicitanteTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblNombreSolicitanteTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblNombreSolicitanteTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 290, 450, 38));

        lblTipoTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblTipoTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 218, 318, 38));

        lblFechaTramite.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFechaTramite.setForeground(new java.awt.Color(196, 4, 67));
        add(lblFechaTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 163, 500, 43));

        lblCosto.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(196, 4, 67));
        lblCosto.setText("Costo:");
        add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 362, 91, 38));

        lblNombreSolicitante.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblNombreSolicitante.setForeground(new java.awt.Color(215, 70, 118));
        lblNombreSolicitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreSolicitante.setText("<html>Nombre del<br>solicitante</html>");
        add(lblNombreSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 271, 190, 76));

        lblTipo.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(196, 4, 67));
        lblTipo.setText("Tipo:");
        add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 218, 72, 38));

        lblFecha.setFont(new java.awt.Font("Amazon Ember", 0, 32)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(196, 4, 67));
        lblFecha.setText("Fecha:");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 163, 100, 43));

        lblTramiteEnCurso.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblTramiteEnCurso.setForeground(new java.awt.Color(196, 4, 67));
        lblTramiteEnCurso.setText("Tramite en curso");
        add(lblTramiteEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 92, 290, 45));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaVentanaConfirmacionLicencia.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción ejecutada al hacer clic en el botón "Aceptar".
     * Este método cierra la vista de confirmación de trámite y vuelve a la vista principal.
     *
     * @param evt Evento de acción.
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCostoTramite;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaTramite;
    private javax.swing.JLabel lblNombreSolicitante;
    private javax.swing.JLabel lblNombreSolicitanteTramite;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoTramite;
    private javax.swing.JLabel lblTramiteEnCurso;
    // End of variables declaration//GEN-END:variables

     /**
     * Carga los datos de la licencia en la vista.
     * Este método establece la fecha de emisión, el tipo de trámite, el nombre del solicitante
     * y el costo de la licencia.
     */
    private void cargarDatosLicencia() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fechaFormateada = formato.format(licenciaDTO.getFechaEmision().getTime());
        
        lblFechaTramite.setText(fechaFormateada);
        lblTipoTramite.setText("Expedición de licencia");
        String nombreCompleto = licenciaDTO.getPersona().getNombres().concat(" "+licenciaDTO.getPersona().getApellidoPaterno());
        lblNombreSolicitanteTramite.setText(nombreCompleto);
        
        String numeroFormateado = String.format("%.2f", licenciaDTO.getCosto());

        lblCostoTramite.setText("$" + numeroFormateado + " MXN");
    }
    
    /**
     * Carga los datos de la placa nueva en la vista para un auto nuevo.
     * Este método establece la fecha de emisión, el tipo de trámite, el nombre del solicitante
     * y el costo de la placa.
     */
    private void cargarDatosPlacaNueva() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fechaFormateada = formato.format(placaNuevaDTO.getFechaEmision().getTime());
        
        lblFechaTramite.setText(fechaFormateada);
        lblTipoTramite.setText("Expedición de placa");
        String nombreCompleto = placaNuevaDTO.getPersona().getNombres().concat(" "+placaNuevaDTO.getPersona().getApellidoPaterno() + " "
                + placaNuevaDTO.getPersona().getApellidoMaterno());
        lblNombreSolicitanteTramite.setText(nombreCompleto);
        
        String numeroFormateado = String.format("%.2f", placaNuevaDTO.getCosto());

        lblCostoTramite.setText("$" + numeroFormateado + " MXN");
    }
    
    /**
     * Carga los datos de la placa nueva en un auto usado.
     * Este método establece la fecha de emisión, el tipo de trámite, el nombre del solicitante
     * y el costo de la placa.
     */
    private void cargarDatosPlacaRenovada() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fechaFormateada = formato.format(placaConsultaDTO.getFechaEmision().getTime());
        
        lblFechaTramite.setText(fechaFormateada);
        lblTipoTramite.setText("Expedición de placa");
        String nombreCompleto = placaConsultaDTO.getPersona().getNombres().concat(" "+placaConsultaDTO.getPersona().getApellidoPaterno() + " "
                + placaConsultaDTO.getPersona().getApellidoMaterno());
        lblNombreSolicitanteTramite.setText(nombreCompleto);
        
        String numeroFormateado = String.format("%.2f", placaConsultaDTO.getCosto());

        lblCostoTramite.setText("$" + numeroFormateado + " MXN");
    }

}
